on:
  push:
    branches:
      - master

env:
  DOTNET_CORE_VERSION: 8.0.x
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GOOGLE_REGION: asia-southeast1

jobs:
  BuildAndDeployApp:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up .NET SDK
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    # Step 3: Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLECRED }}

    # Step 4: Configure Google Cloud
    - name: Configure Google Cloud
      run: |
        gcloud config set project ${{ env.GOOGLE_PROJECT_ID }}
        gcloud config set compute/region ${{ env.GOOGLE_REGION }}

    # Step 5: Deploy to App Engine
    - name: Deploy to App Engine
      run: |
        dotnet restore
        dotnet publish -c Release -o ./publish
        cp CcStore/app.yaml ./publish/  # Adjust the path to the app.yaml file
        gcloud app deploy ./publish/app.yaml --quiet