on:
  push:
    branches:
      - master

env:
  DOTNET_CORE_VERSION: 8.x
  GOOGLE_PROJECT_ID: ${{ secrets.GOOGLE_PROJECT_ID }}
  GOOGLE_REGION: asia-southeast1
  IMAGE_NAME: ccstore-app
  IMAGE_TAG: latest

jobs:
  BuildAndDeployApp:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the source code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Set up .NET SDK (not strictly needed for containerization, but can be useful for debugging)
    - name: Set up .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: ${{ env.DOTNET_CORE_VERSION }}

    # Step 3: Authenticate with Google Cloud
    - name: Authenticate with Google Cloud
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GOOGLECRED }}

    # Step 4: Build the Docker image
    - name: Build Docker image
      run: |
        docker build -t gcr.io/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} .

    # Step 5: Push Docker image to Google Container Registry
    - name: Push Docker image to Google Container Registry
      run: |
        docker push gcr.io/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}

    # Step 6: Deploy to Cloud Run (or GKE)
    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy ${{ env.IMAGE_NAME }} \
          --image gcr.io/${{ env.GOOGLE_PROJECT_ID }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }} \
          --platform managed \
          --region ${{ env.GOOGLE_REGION }} \
          --allow-unauthenticated \
          --quiet
